# This workflow will do a clean installation of node dependencies
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # --- මෙන්න මෙතන තමයි වෙනස් කළේ ---
    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Start NETHMINA-OFC Bot
      run: npm start
